GET http://localhost:8000/categories/

###
GET http://localhost:8000/categories/8ad3d3c4-9be1-498e-a3dc-8daee1602f0b/

###
POST http://localhost:8000/categories/
Content-Type: application/json

{
    "name": "Movie"
}

###

PUT http://localhost:8000/categories/f325c276-4d9e-47a2-a4ce-c151bd0e0074/
Content-Type: application/json

{
  "name": "Movie2",
  "description": null,
  "is_active": false
}

###

DELETE http://localhost:8000/categories/7af68f5b-772a-472c-b36e-a68ca225eab3/
Content-Type: application/json
