version: '3'

services:
  app:
    build: .
    container_name: micro-videos-python-app
    command: ./.docker/start-app.sh
    volumes:
      - .:/home/python/app
    ports:
      - 8000:8000
  db:
    image: mysql:8.0.34-debian
    container_name: micro-videos-python-db
    environment:
      - MYSQL_DATABASE=micro-videos
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated